services:
  stellar:
    image: stellar/quickstart:testing
    ports:
      - "8000:8000"
      - "6061:6061"
    command:
      ["--local", "--enable-soroban-rpc", "--enable-soroban-rpc-admin-endpoint"]
    networks:
      - stellar-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - stellar
    networks:
      - stellar-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - stellar-network

networks:
  stellar-network:
    driver: bridge
